# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/four_sixteen_con.xdc

# Block Designs: bd/four_sixteen/four_sixteen.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==four_sixteen || ORIG_REF_NAME==four_sixteen} -quiet] -quiet

# IP: bd/four_sixteen/ip/four_sixteen_three_eight_0_0/four_sixteen_three_eight_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==four_sixteen_three_eight_0_0 || ORIG_REF_NAME==four_sixteen_three_eight_0_0} -quiet] -quiet

# IP: bd/four_sixteen/ip/four_sixteen_three_eight_1_0/four_sixteen_three_eight_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==four_sixteen_three_eight_1_0 || ORIG_REF_NAME==four_sixteen_three_eight_1_0} -quiet] -quiet

# IP: bd/four_sixteen/ip/four_sixteen_util_vector_logic_0_1/four_sixteen_util_vector_logic_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==four_sixteen_util_vector_logic_0_1 || ORIG_REF_NAME==four_sixteen_util_vector_logic_0_1} -quiet] -quiet

# IP: bd/four_sixteen/ip/four_sixteen_util_vector_logic_1_6/four_sixteen_util_vector_logic_1_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==four_sixteen_util_vector_logic_1_6 || ORIG_REF_NAME==four_sixteen_util_vector_logic_1_6} -quiet] -quiet

# IP: bd/four_sixteen/ip/four_sixteen_util_vector_logic_1_7/four_sixteen_util_vector_logic_1_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==four_sixteen_util_vector_logic_1_7 || ORIG_REF_NAME==four_sixteen_util_vector_logic_1_7} -quiet] -quiet

# IP: bd/four_sixteen/ip/four_sixteen_util_vector_logic_1_8/four_sixteen_util_vector_logic_1_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==four_sixteen_util_vector_logic_1_8 || ORIG_REF_NAME==four_sixteen_util_vector_logic_1_8} -quiet] -quiet

# IP: bd/four_sixteen/ip/four_sixteen_util_vector_logic_1_9/four_sixteen_util_vector_logic_1_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==four_sixteen_util_vector_logic_1_9 || ORIG_REF_NAME==four_sixteen_util_vector_logic_1_9} -quiet] -quiet

# IP: bd/four_sixteen/ip/four_sixteen_util_vector_logic_1_10/four_sixteen_util_vector_logic_1_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==four_sixteen_util_vector_logic_1_10 || ORIG_REF_NAME==four_sixteen_util_vector_logic_1_10} -quiet] -quiet

# IP: bd/four_sixteen/ip/four_sixteen_util_vector_logic_2_1/four_sixteen_util_vector_logic_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==four_sixteen_util_vector_logic_2_1 || ORIG_REF_NAME==four_sixteen_util_vector_logic_2_1} -quiet] -quiet

# IP: bd/four_sixteen/ip/four_sixteen_util_vector_logic_3_0/four_sixteen_util_vector_logic_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==four_sixteen_util_vector_logic_3_0 || ORIG_REF_NAME==four_sixteen_util_vector_logic_3_0} -quiet] -quiet

# IP: bd/four_sixteen/ip/four_sixteen_util_vector_logic_4_0/four_sixteen_util_vector_logic_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==four_sixteen_util_vector_logic_4_0 || ORIG_REF_NAME==four_sixteen_util_vector_logic_4_0} -quiet] -quiet

# IP: bd/four_sixteen/ip/four_sixteen_util_vector_logic_1_11/four_sixteen_util_vector_logic_1_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==four_sixteen_util_vector_logic_1_11 || ORIG_REF_NAME==four_sixteen_util_vector_logic_1_11} -quiet] -quiet

# IP: bd/four_sixteen/ip/four_sixteen_util_vector_logic_2_2/four_sixteen_util_vector_logic_2_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==four_sixteen_util_vector_logic_2_2 || ORIG_REF_NAME==four_sixteen_util_vector_logic_2_2} -quiet] -quiet

# IP: bd/four_sixteen/ip/four_sixteen_util_vector_logic_3_1/four_sixteen_util_vector_logic_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==four_sixteen_util_vector_logic_3_1 || ORIG_REF_NAME==four_sixteen_util_vector_logic_3_1} -quiet] -quiet

# IP: bd/four_sixteen/ip/four_sixteen_util_vector_logic_4_1/four_sixteen_util_vector_logic_4_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==four_sixteen_util_vector_logic_4_1 || ORIG_REF_NAME==four_sixteen_util_vector_logic_4_1} -quiet] -quiet

# IP: bd/four_sixteen/ip/four_sixteen_util_vector_logic_5_0/four_sixteen_util_vector_logic_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==four_sixteen_util_vector_logic_5_0 || ORIG_REF_NAME==four_sixteen_util_vector_logic_5_0} -quiet] -quiet

# IP: bd/four_sixteen/ip/four_sixteen_util_vector_logic_6_0/four_sixteen_util_vector_logic_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==four_sixteen_util_vector_logic_6_0 || ORIG_REF_NAME==four_sixteen_util_vector_logic_6_0} -quiet] -quiet

# IP: bd/four_sixteen/ip/four_sixteen_util_vector_logic_7_0/four_sixteen_util_vector_logic_7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==four_sixteen_util_vector_logic_7_0 || ORIG_REF_NAME==four_sixteen_util_vector_logic_7_0} -quiet] -quiet

# IP: bd/four_sixteen/ip/four_sixteen_util_vector_logic_8_0/four_sixteen_util_vector_logic_8_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==four_sixteen_util_vector_logic_8_0 || ORIG_REF_NAME==four_sixteen_util_vector_logic_8_0} -quiet] -quiet

# XDC: bd/four_sixteen/four_sixteen_ooc.xdc
